---

- name: Configure Cisco IOS
  hosts: all
  gather_facts: no
  connection: local
  ansible_become: yes
  ansible_become_method: enable


  tasks:

    # -----------------------------------------------------
    #
    # Facts
    #
    - name: Collect all facts from the device
      ios_facts:
        gather_subset: all


    # -----------------------------------------------------
    #  
    #  Probe for features
    #
    # - name: Probe netwflow feature
    #   ios_config:
    #     lines: 
    #       - "ip flow-export destination {{test_address}} 65535"
    #       - "no ip flow-export destination {{test_address}} 65535"
    #   register: netflow_is_supported
    #   ignore_errors: yes

    # -----------------------------------------------------
    #
    # General settings
    #
    - name: Configure global settings
      ios_config:
        lines: "{{ item }}"
      with_items:
              #- ip cef
        - service nagle
        - service tcp-keepalives-in
        - service tcp-keepalives-out
        - service timestamps debug datetime msec localtime show-timezone
        - service timestamps log datetime msec localtime show-timezone
        - service password-encryption
        - no service dhcp
        - logging buffered 16384
        - no logging console
        - no enable password
    #    - "enable secret 0 {{enable_secret}}"
    #    - "username {{ user_name }} secret {{ user_password }}"
        - no ip http server
        - no ip http secure-server
        - ip subnet-zero
        - ip classless
        - no service pad
        - no ip source-route
        - no ip finger
          #- no ip bootp server
        - no service dhcp
        - no service udp-small-servers
        - login on-failure log
        - login on-success log
    # TODO: move some lines to other sections
    # TODO: enable password unless Radius or TACACS+
    # TODO: multiple local username ... ???
    # TODO: some of the above must be skipped if they are already in the current config
    #        (facts: ansible_net_config)

    # - name: Disable DNS lookups (conditional)
    #   ios_config:
    #     lines: 
    #     - no ip domain-lookup
    #   when: not domain_lookup

    - debug:
        msg: "********** DNS lookups are disabled **********"

    - name: Configure hostname and domain name
      ios_config:
        lines:
          - hostname "{{ inventory_hostname }}"
          - "ip domain-name {{domain_name|default('example.com')}}"

    - name: Configure CDP globally
      ios_config:
        lines: no cdp run
      when: enable_cdp is not defined or not enable_cdp


    # -----------------------------------------------------
    #
    # AAA (no TACAS+ or Radius)
    #
    - name: Configure AAA
      ios_config:
        lines: "{{ item }}"
      with_items:
        - aaa new-model

    - name: Configure local-only AAA (conditional)
      ios_config:
        lines: "{{ item }}"
      with_items:
        - aaa authentication login default local-case
        - aaa authentication enable default enable
        - aaa authorization commands 15 default local
      when: tacacs_servers is undefined and radius_servers is undefined

    # -----------------------------------------------------
    #
    # TACACS+
    #
    - name: Configure TACACS+ AAA (conditional)
      ios_config:
        lines: "{{ item }}"
      with_items:
        - aaa authentication login default group tacacs+ local-case
        - aaa authentication enable default group tacacs+ enable
        - aaa authorization commands 15 default group tacacs+ local
        - aaa accounting exec default stop-only group tacacs+
        - aaa accounting commands 15 default stop-only group tacacs+
        - aaa accounting network default stop-only group tacacs+
      when: tacacs_servers is defined

    - name: Configure TACACS+ servers (conditional)
      ios_config:
        lines: "tacacs-server {{ item }}"
      with_items: "{{ tacacs_servers }}"
      when: tacacs_servers is defined

    - name: Configure TACACS+ key
      ios_config:
        lines: "tacacs-server key {{tacacs_server_key}}"
      when: tacacs_servers is defined and tacacs_server_key is defined

    - name: Configure TACACS+ timeout
      ios_config:
        lines: "tacacs-server timeout {{tacacs_server_timeout}}"
      when: tacacs_servers is defined and tacacs_server_timeout is defined

    - name: Configure TACACS+ source interface
      ios_config:
        lines: "ip tacacs source-interface {{tacacs_source_interface}}"
      when: tacacs_servers is defined and tacacs_source_interface is defined


    # TODO: configure AAA if no TACACS or Radius servers were given?

    # -----------------------------------------------------
    #
    # Radius TODO
    #


    # -----------------------------------------------------
    #
    # Archive
    #
    # TODO: can this be done in one go through replace: block????
    # TODO: logging size parameter
    - name: Configure archiving (archive)
      ios_config:
        
    - name: Configure archiving (archive/log config)
      ios_config:
        lines: log config
        parents: archive

    - name: Configure archiving (archive/log config/*)
      ios_config:
        lines: "{{ item }}"
        parents:
          - archive
          - log config
      with_items:
        - logging enable
        - logging size 500
        - notify syslog
        - hidekeys


    # -----------------------------------------------------
    #
    # Exception core file
    #
    - name: Exception core file to FTP server (optional)
      ios_config:
        lines: "{{ item }}"
      with_items:
        - "ip ftp username {{exception_ftp_username}}"
        - "ip ftp password {{exception_ftp_password}}"
        - "exception core-file {{ inventory_hostname }}-core"
        - "exception protocol ftp"
        - "exception dump {{exception_ftp_server}}"
      when: exception_ftp_server is defined and exception_ftp_username is defined and exception_ftp_password is defined

    # -----------------------------------------------------
    #
    # NTP and Time
    #
    - name: NTP servers
      ios_config:
        lines: "ntp server {{ item }}"
      with_items: "{{ ntp_servers }}"
      when: ntp_servers is defined 

    # - name: NTP and time settings
    #   ios_config:
    #     lines: "{{ item }}"
    #   with_items:
    #     - "clock timezone {{timezone_name|default('UTC')}} {{timezone_offset_hours|default(0)}} {{timezone_offset_minutes|default(omit)}}"


    # TODO: configure advanced NTP settings.
    # TODO: configure router as NTP server itself plus ACL


    # -----------------------------------------------------
    #
    # loopback0 and null0 interfaces
    #
    - name: Configure loopback0 interface
      ios_config:
        # Don't put 'no ...' lines in here!!!
        lines:
          - "interface Loopback 0"
          - "ip address {{loopback_address}} 255.255.255.255"
          - "no ip redirects"
          - "no ip unreachables"
          - "no ip proxy-arp"

    - name: Configure null0 interface
      ios_config:
        # Don't put 'no ...' lines in here!!!
        lines:
          - "interface Null 0"
          - "no ip unreachables"


    # TODO ethernet interface specifics?

    # -----------------------------------------------------
    #
    # Netflow
    # TODO: check whether IOS supports netflow
    #
    - name: Configure netflow (settings)
      ios_config:
        lines: "{{ item }}"
      when: netflow_destinations is defined and netwflow_is_supported is defined
      with_items:
        - "ip flow-export source {{netflow_source_interface|default('loopback0')}}"
        - "ip flow-export version {{netflow_version|default('5')}} origin-as"

    - name: Configure netflow (destinations)
      ios_config:
        lines: "ip flow-export destination {{item.host}} {{item.port}}"
      when: netflow_destinations is defined and netwflow_is_supported is defined
      with_items: "{{netflow_destinations}}"


    # -----------------------------------------------------
    #
    # Logging
    #
    - name: Configure logging (settings)
      ios_config:
        
        lines: "{{ item }}"
      when: logging_destinations is defined
      with_items:
        - "logging trap {{logging_level|default('informational')}}"
        - "logging facility {{logging_facility|default('local5')}}"
        - "logging source-interface {{logging_source_interface|default('loopback0')}}"

    - name: Configure logging (destinations)
      ios_config:
        
        lines: "logging {{item}}"
      when: logging_destinations is defined
      with_items: "{{logging_destinations}}"


    # -----------------------------------------------------
    #
    #  SNMP
    #
    - name: SNMP access list
      ios_config:
        lines: "access-list 20 permit {{item}}"
        #before: "no access-list 20"
        after: access-list 20 deny any log
      when: snmp_managers is defined
      with_items: "{{snmp_managers}}"

    - name: SNMP read-only community
      ios_config:
        lines: "snmp-server community {{item}} ro 20"
      when: snmp_readonly_communities is defined
      with_items: "{{snmp_readonly_communities}}"

    - name: SNMP read-write community
      ios_config:
        lines: "snmp-server community {{item}} rw 20"
      when: snmp_readonly_communities is defined
      with_items: "{{snmp_readwrite_communities}}"

    # TODO: SNMP trap destinations
    # TODO: SNMPv3
    # TODO: snmp_unsafe_communities


    # -----------------------------------------------------
    #
    # Banner
    #
    - name: Configure login banner
      ios_banner:
        banner: login
        text: |
              ==========================================================================================
                              UNAUTHORIZED ACCESS TO THIS DEVICE IS PROHIBITED
              You must have explicit, authorized permission to access or configure this device.
              Unauthorized attempts and actions to access or use this system may result in civil and/or
              criminal penalties.
              All activities performed on this device are logged and monitored.
              ==========================================================================================
        state: present


    # -----------------------------------------------------
    #
    # Line access
    #
    - name: login
      ios_config:
        lines:
          - login block-for 100 attempts 15 within 100
          - login quiet-mode access-class 100
      when: vty_acl_sources is defined

    - name: line con 0
      ios_config:
        parents:
          - line con 0
        lines:
          - exec-timeout 15 0

            # TODO: check for linx aux 0 first
            #    - name: line aux 0
            #      ios_config:
            #        
            #        parents:
            #          - line aux 0
            #        lines:
            #          - exec-timeout 15 0

    - name: line vty 0 3 access list
      ios_config:
        lines: "access-list 100 permit tcp {{item.host}} {{item.mask|default(omit)}} host 0.0.0.0 eq 22 log-input"
        # access-list 100 permit tcp 10.0.0.0 192.168.0.0 host 0.0.0.0 eq 22 log-input
        after: access-list 100 deny ip any any log-input
        before: no access-list 100
      when: vty_acl_sources is defined
      with_items: "{{vty_acl_sources}}"

    - name: line vty 0 3
      ios_config:
        parents:
        - line vty 0 3
        lines:
        - transport input ssh
        - exec-timeout 15 0
        - ip ssh version 2

    - name: line vty 0 3 ACL
      ios_config:
        lines:
          - access-class 100 in
        parents:
          - line vty 0 3
      when: vty_acl_sources is defined

    - name: line vty 4 access list
      ios_config:
        lines: "access-list 105 permit tcp host {{item}} host 0.0.0.0 range 22 log-input"
        after: access-list 105 deny ip any any log-input
        before: no access-list 105
      when: vty_acl_secure_sources is defined
      with_items: "{{vty_acl_secure_sources}}"

    - name: line 4 vty
      ios_config:
        parents:
        - line vty 4
        lines:
        - exec-timeout 15 0
        - transport input ssh
        - access-class 100 in
      when: vty_acl_secure_sources is defined


    # -----------------------------------------------------
    #
    # Save config
    #
 #   - name: Save running-config to startup-config
 #     ios_command:
 #       
 #       commands: write
